as3/onlinestore/config/routes.rb
Rails.application.routes.draw do
  
  root "shopper#index", as: "shopper"
  #root "access#new"
  get 'shopper/', to: 'shopper#index'
  get 'shopper/index', to: 'shopper#index'
  get 'shopper/show', to: "shopper#show"
  get 'admin/', to: 'admin#index'
  get 'login/', to: 'access#new'
  post 'login/', to: 'access#create'
  delete 'logout/', to: 'access#destroy'
  resources :users
  resources :orders
  resources :lineitems
  resources :carts
  
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

as3/onlinestore/app/models/cart.rb
class Cart < ApplicationRecord
	has_many :lineitems, dependent: :destroy
	
 def add_item(product_id)
        current_item = lineitems.find_by(product_id: product_id)
        
        # aggregate duplicate product
        if current_item == nil
            current_item = lineitems.build(product_id: product_id)
        else
            current_item.quantity += 1
        end

        return current_item
    end

    def total_price
		sum = 0
        lineitems.each do |lineitem|
            sum += lineitem.product.price * lineitem.quantity
        end
		return sum
    end
end

as3/onlinestore/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
	session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to shopper_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_cart
    #  @cart = Cart.find(params[:id])
    #end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

as3/onlinestore/app/helpers/carts_helper.rb
module CartsHelper
end

as3/onlinestore/app/views/carts/_cart.html.erb
<h3> Items in your shopping cart </h3>

<table>
    <thead>
        <th>Item name</th>
        <th>Quality</th>
        <th>Price</th>
    </thead>
	
	<% @cart.lineitems.each do |lineitem|%>
		<tr>
            <td><%= lineitem.product.name %></td>
            <td><%= lineitem.quantity %></td>
            <td><%= lineitem.product.price * lineitem.quantity %></td>
        </tr>
    <% end %>
	<tr>
        <td colspan="2">Total</td>
        <td><%= @cart.total_price %></td>
    </tr>
</table>
<br>
<div>
    <%= button_to 'Empty Cart', @cart, method: :delete, data: {confirm: 'Are you sure?'} %>
	<%= button_to 'Check Out', new_order_path, method: :get %>
</div>

as3/onlinestore/app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

as3/onlinestore/app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

as3/onlinestore/app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

as3/onlinestore/app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

as3/onlinestore/app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h3> Items in your shopping cart </h3>

<table>
    <thead>
        <th>Item name</th>
        <th>Quality</th>
        <th>Price</th>
    </thead>
	
	<% @cart.lineitems.each do |lineitem|%>
		<tr>
            <td><%= lineitem.product.name %></td>
            <td><%= lineitem.quantity %></td>
            <td><%= lineitem.product.price * lineitem.quantity %></td>
        </tr>
    <% end %>
	<tr>
        <td colspan="2">Total</td>
        <td><%= @cart.total_price %></td>
    </tr>
</table>
<br>
<div>
    <%= button_to 'Empty Cart', @cart, method: :delete, data: {confirm: 'Are you sure?'} %>
</div>