as3/onlinestore/config/routes.rb
Rails.application.routes.draw do
  
  root "shopper#index", as: "shopper"
  #root "access#new"
  get 'shopper/', to: 'shopper#index'
  get 'shopper/index', to: 'shopper#index'
  get 'shopper/show', to: "shopper#show"
  get 'admin/', to: 'admin#index'
  get 'login/', to: 'access#new'
  post 'login/', to: 'access#create'
  delete 'logout/', to: 'access#destroy'
  resources :users
  resources :orders
  resources :lineitems
  resources :carts
  
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

as3/onlinestore/app/models/order.rb
class Order < ApplicationRecord
	has_many :lineitems, dependent: :destroy
	
	PAYMENT_TYPES = ["check", "credit card", "venmo", "paypal"]
	validates :name, :address, :email, presence: true
	
	validates :paytype, inclusion: PAYMENT_TYPES
	
	def add_items_from_cart(cart)
		cart.lineitems.each do |item|
			item.cart_id = nil
			item.order_id = self.id
		end
	end
end

as3/onlinestore/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
	if @cart.lineitems.empty?
		redirect_to shopper_url, notice: "Your shopping cart is empty."
	end
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
	@order.add_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        format.html { redirect_to shopper_url, notice: 'Thank you for your order.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :paytype)
    end
end

as3/onlinestore/app/helpers/orders_helper.rb
module OrdersHelper
end

as3/onlinestore/app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, rows:3, cols:40%>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :paytype %>
    <%= form.select :paytype, Order::PAYMENT_TYPES, prompt: 'select a payment method' %>
  </div>

  <div class="actions">
    <%= form.submit 'Place Order' %>
  </div>
<% end %>

as3/onlinestore/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

as3/onlinestore/app/views/orders/index.html.erb
<% if notice%>
<p id="notice"><%= notice %></p>
<%end%>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Paytype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.paytype %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

as3/onlinestore/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', shopper_path %>

as3/onlinestore/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Paytype:</strong>
  <%= @order.paytype %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>