as3/onlinestore/config/routes.rb
Rails.application.routes.draw do
  
  root "shopper#index", as: "shopper"
  #root "access#new"
  get 'shopper/', to: 'shopper#index'
  get 'shopper/index', to: 'shopper#index'
  get 'shopper/show', to: "shopper#show"
  get 'admin/', to: 'admin#index'
  get 'login/', to: 'access#new'
  post 'login/', to: 'access#create'
  delete 'logout/', to: 'access#destroy'
  resources :users
  resources :orders
  resources :lineitems
  resources :carts
  
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

as3/onlinestore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onlinestore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name%>">
	<div id="banner">
		<%= @page_title || "Our Products"%>
	</div>
	
	<div id="columns">
		<div id="side">
			<div id="cart">
				<% if @cart && !['products', 'admin', 'access', 'users'].include?(controller.controller_name) %>
                <%= render @cart %>
                <% end %>
			</div>
			<% if session[:user_id] %>
				<ul>
					<li><%= link_to 'Shoppings', shopper_path %></li>
					<li><%= link_to 'Orders', orders_path %></li>
					<li><%= link_to 'Products', products_path %></li>
					<li><%= link_to 'Users', users_path %></li>
				</ul>
				<%= button_to 'Logout', logout_path, method: :delete %>
			<% end %>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
  </body>
</html>